/**
 * @file solvers.hpp
 * @brief Complex Numerical Engine for Algebraic Systems.
 * 
 * Objective:
 * This file encapsulates the heavy mathematical logic required to resolve
 * the linear and non-linear systems generated by physical models.
 * 
 * Architectural Rationale:
 * Segregating solvers isolates the "Brute Force" of numerical analysis ($Ax=b$, 
 * $f(x)=0$) from the "Elegance" of physical governing equations. 
 * This ensures that improvements in matrix inversion or convergence 
 * algorithms (e.g., swapping LU for iterative CG) do not require physical 
 * module refactoring.
 * 
 * Strategic Importance:
 * It enables "Plug-and-Play" numerics. A developer can independently 
 * optimize how a system is solved without knowing the specific physics 
 * (Pressure vs Temperature) that generated the system.
 */
#pragma once
#include "lib/interfaces.hpp"
#include <vector>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <functional>



#include "interfaces.hpp"

namespace num {
using namespace top;

/**
 * @brief Dense LU Linear Solver with Partial Pivoting.
 */
class LUSolver : public ISolver {
public:
    Vector solve(const SparseMatrix& A, const Vector& b) override {
        // LU currently works on dense Matrix. For now, we convert Sparse to Dense.
        // In a real HPC environment, we would use a Sparse LU like SuperLU.
        Matrix dense_A = A.to_dense(); 
        return solve_system(dense_A, b);
    }

    Vector solve_system(Matrix A, Vector b) {
        int n = b.size();
        for (int i = 0; i < n; i++) {
            int pivot = i;
            for (int j = i + 1; j < n; j++) {
                if (std::abs(A[j][i]) > std::abs(A[pivot][i])) pivot = j;
            }
            std::swap(A[i], A[pivot]);
            std::swap(b[i], b[pivot]);
            
            if (std::abs(A[i][i]) < 1e-18) continue; 
            
            for (int j = i + 1; j < n; j++) {
                double factor = A[j][i] / A[i][i];
                b[j] -= factor * b[i];
                for (int k = i; k < n; k++) {
                    A[j][k] -= factor * A[i][k];
                }
            }
        }
        Vector x(n, 0.0);
        for (int i = n - 1; i >= 0; i--) {
            if (std::abs(A[i][i]) < 1e-18) continue;
            double sum = 0;
            for (int j = i + 1; j < n; j++) sum += A[i][j] * x[j];
            x[i] = (b[i] - sum) / A[i][i];
        }
        return x;
    }
};

/**
 * @brief Specialized Tridiagonal Solver (Thomas Algorithm).
 */
class LinearTridiagonalSolver : public ISolver {
public:
    Vector solve(const SparseMatrix& A, const Vector& b) override { 
        Matrix dense_A = A.to_dense(); 
        return solve_system(dense_A, b);
    }

    Vector solve_system(const Matrix& A, const Vector& b) {
        int n = b.size();
        if (n == 0) return {};
        if (n == 1) return {b[0] / A[0][0]};

        Vector c_star(n, 0.0);
        Vector d_star(n, 0.0);
        Vector x(n, 0.0);

        // Forward elimination
        c_star[0] = A[0][1] / A[0][0];
        d_star[0] = b[0] / A[0][0];

        for (int i = 1; i < n; i++) {
            double den = (A[i][i] - A[i][i-1] * c_star[i-1]);
            double m = 1.0 / den;
            if (i < n - 1) {
                c_star[i] = A[i][i+1] * m;
            }
            d_star[i] = (b[i] - A[i][i-1] * d_star[i-1]) * m;
        }

        // Backward substitution
        x[n-1] = d_star[n-1];
        for (int i = n - 2; i >= 0; i--) {
            x[i] = d_star[i] - c_star[i] * x[i+1];
        }

        return x;
    }
};

/**
 * @brief BiCGSTAB (Biconjugate Gradient Stabilized) Solver.
 */
class BiCGSTABSolver : public ISolver {
public:
    double tolerance = 1e-8;
    int max_iterations = 1000;
    bool verbose = false;

    Vector solve(const SparseMatrix& A, const Vector& b) override {
        return solve_system(A, b, tolerance, max_iterations, verbose);
    }

    static Vector solve_system(const SparseMatrix& A, 
                               const std::vector<double>& b, 
                               double tol = 1e-8, 
                               int max_iter = 1000,
                               bool verbose = false) {
        int n = (int)b.size();
        std::vector<double> x(n, 0.0);
        
        std::vector<double> r(n), r_hat(n), v(n), p(n), s(n), t(n);
        std::vector<double> Ax0 = A.multiply(x);
        
        #pragma omp parallel for
        for (int i = 0; i < n; ++i) {
            r[i] = b[i] - Ax0[i];
            r_hat[i] = r[i];
            v[i] = 0.0;
            p[i] = 0.0;
        }
        
        double rho = 1.0, alpha = 1.0, omega = 1.0;
        
        for (int i = 0; i < max_iter; ++i) {
            double rho_new = 0.0;
            #pragma omp parallel for reduction(+:rho_new)
            for(int j=0; j<n; ++j) rho_new += r_hat[j] * r[j];
            
            if (std::abs(rho_new) < 1e-60) break;
            
            if (i == 0) {
                #pragma omp parallel for
                for(int j=0; j<n; ++j) p[j] = r[j];
            } else {
                double beta = (rho_new / rho) * (alpha / omega);
                #pragma omp parallel for
                for(int j=0; j<n; ++j) {
                    p[j] = r[j] + beta * (p[j] - omega * v[j]);
                }
            }
            
            v = A.multiply(p);
            double v_dot_rhat = 0.0;
            #pragma omp parallel for reduction(+:v_dot_rhat)
            for(int j=0; j<n; ++j) v_dot_rhat += r_hat[j] * v[j];
            
            if (std::abs(v_dot_rhat) < 1e-60) break;

            alpha = rho_new / v_dot_rhat;
            
            double norm_s = 0.0;
            #pragma omp parallel for reduction(+:norm_s)
            for(int j=0; j<n; ++j) {
                s[j] = r[j] - alpha * v[j];
                norm_s += s[j] * s[j];
            }
            norm_s = std::sqrt(norm_s);
            
            if (norm_s < tol) {
                #pragma omp parallel for
                for(int j=0; j<n; ++j) x[j] += alpha * p[j];
                return x;
            }
            
            t = A.multiply(s);
            double t_dot_t = 0.0, t_dot_s = 0.0;
            #pragma omp parallel for reduction(+:t_dot_t, t_dot_s)
            for(int j=0; j<n; ++j) {
                t_dot_t += t[j] * t[j];
                t_dot_s += t[j] * s[j];
            }
            
            omega = (t_dot_t < 1e-60) ? 0.0 : t_dot_s / t_dot_t;
            
            double norm_r = 0.0;
            #pragma omp parallel for reduction(+:norm_r)
            for(int j=0; j<n; ++j) {
                x[j] += alpha * p[j] + omega * s[j];
                r[j] = s[j] - omega * t[j];
                norm_r += r[j] * r[j];
            }
            norm_r = std::sqrt(norm_r);
            
            if (norm_r < tol) return x;
            rho = rho_new;
        }
        
        return x;
    }
};

/**
 * @brief Conjugate Gradient Linear Solver.
 */
class ConjugateGradientSolver : public ISolver {
public:
    double tolerance = 1e-6;
    int max_iterations = 1000;

    Vector solve(const SparseMatrix& A, const Vector& b) override {
        Vector guess(b.size(), 0.0);
        return solve_system(A, b, guess, tolerance, max_iterations);
    }
    
    Vector solve_system(const SparseMatrix& A, const Vector& b, Vector x0, 
                        double tol = 1e-6, int max_iter = 1000) {
        int n = b.size();
        Vector x = x0;
        Vector r = subtract(b, A.multiply(x));
        Vector p = r;
        double rsold = dot(r, r);

        for (int i = 0; i < max_iter; i++) {
            Vector Ap = A.multiply(p);
            double alpha = rsold / dot(p, Ap);
            x = add(x, scale(p, alpha));
            r = subtract(r, scale(Ap, alpha));
            double rsnew = dot(r, r);
            if (std::sqrt(rsnew) < tol) break;
            p = add(r, scale(p, rsnew / rsold));
            rsold = rsnew;
        }
        return x;
    }

private:
    double dot(const Vector& a, const Vector& b) {
        double res = 0;
        #pragma omp parallel for reduction(+:res)
        for (int i = 0; i < (int)a.size(); i++) res += a[i] * b[i];
        return res;
    }
    Vector add(Vector a, const Vector& b) {
        #pragma omp parallel for
        for (int i = 0; i < (int)a.size(); i++) a[i] += b[i];
        return a;
    }
    Vector subtract(Vector a, const Vector& b) {
        #pragma omp parallel for
        for (int i = 0; i < (int)a.size(); i++) a[i] -= b[i];
        return a;
    }
    Vector scale(Vector a, double s) {
        #pragma omp parallel for
        for (int i = 0; i < (int)a.size(); i++) a[i] *= s;
        return a;
    }
};

} // namespace num
